export const actionsTypes = {
    ADD_NEW_MEETUP_SET_REQUEST_STATUS: 'addNewMeetup/SET_REQUEST_STATUS',
    ADD_NEW_MEETUP_SUBMIT_NEW_MEETUP: 'addNewMeetup/SUBMIT_NEW_MEETUP',

    ALL_MEETUPS_INIT : 'ALL_MEETUPS_INIT',
    ALL_MEETUPS_SAVE_STATE: 'ALL_MEETUPS_SAVE_STATE',
    ALL_MEETUPS_SET_REQUEST_STATUS: 'ALL_MEETUPS_SET_REQUEST_STATUS',
    ALL_MEETUP_DELETE: 'ALL_MEETUP_DELETE',

    FAVORITES_TOGGLE: 'FAVORITES_TOGGLE',
    FAVORITES_MEETUPS_SET_REQUEST_STATUS: 'FAVORITES_MEETUPS_SET_REQUEST_STATUS',

    ERROR_SET_CRITICAL_ERROR: 'ERROR_SET_CRITICAL_ERROR',
    ERROR_SET_ERROR: 'ERROR_SET_ERROR',
    ERROR_RESET:'ERROR_RESET',

    SHOW_NOTIFICATION_MESSAGE: 'SHOW_NOTIFICATION_MESSAGE',
    SET_NOTIFICATION_MESSAGE: 'SET_NOTIFICATION_MESSAGE',
    RESET_NOTIFICATION: 'RESET_NOTIFICATION',
}
