export const actionsTypes = {
    ADD_NEW_MEETUP_SET_REQUEST_STATUS: 'addNewMeetup/SET_REQUEST_STATUS',
    ADD_NEW_MEETUP_SUBMIT_NEW_MEETUP: 'addNewMeetup/SUBMIT_NEW_MEETUP',

    ALL_MEETUPS_INIT : 'ALL_MEETUPS_INIT',
    ALL_MEETUPS_SAVE_STATE: 'ALL_MEETUPS_SAVE_STATE',
    ALL_MEETUPS_SET_REQUEST_STATUS: 'ALL_MEETUPS_SET_REQUEST_STATUS',

    FAVORITES_ADD_STATE: 'FAVORITES_ADD_STATE',
    FAVORITES_REMOVE_STATE: 'FAVORITES_REMOVE_STATE',
    FAVORITES_IS_FAVORITE: 'FAVORITES_IS_FAVORITE',
    FAVORITES_SET_STATE: 'FAVORITES_SET_STATE',
    FAVORITES_INIT: 'FAVORITES_INIT',
}
